var name = prompt("Enter a name: ", "")
var gender = prompt("What's the gender of the person?", "")
var age = prompt("How old are you?", "")
var height = prompt("How tall are you?(cm)", "")
var grade = prompt("Which grade are you in?", "")
var mood = prompt("What's your mood?", "")
var sib = prompt("How many siblings do you have?", "")

document.write("So here is the short story you could use when you introduce yourself:")
document.write("<br><br>")
document.write(`My name is ${name}, I am a grade ${grade} student.`)
document.write("<br><br>")
document.write(`I am only ${height} cm tall so I should sleep more.`)
document.write("<br><br>")
document.write(`I have ${sib} siblings which I enjoy my life.`)
document.write("<br><br>")
document.write(`I have lived for ${age} years.`)
document.write("<br><br>")
document.write(`I am ${mood} today. It is always nice to make new friends and I am happy to know all of you better.`)
document.write("<br><br>")
document.write(`Again, my name is ${name}.`)